# Inserts a blank line between shell prompts
add_newline = true

# Use custom format
format = '$username$all'

[username]
style_user = '#01a252 bold'
style_root = '#db2d20 bold'
format = '[$user]($style) in '
disabled = false
show_always = true

# Replace the '❯' symbol in the prompt with '➜'
[character]
success_symbol = '[❯](bold #01a252)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false
